---

- name: Create root directory for riemann
  sudo: yes
  file:
    state: directory
    path: "{{ riemann_root }}"
    owner: "{{ riemann_user }}"
    group: "{{ riemann_user }}"

- name: Download Riemann release
  sudo: yes
  get_url:
    url: "https://github.com/riemann/riemann/releases/download/{{ riemann_version }}/riemann_{{ riemann_version }}_all.deb"
    dest: "{{ riemann_download_dir }}/riemann-{{ riemann_version }}_all.deb"

- name: Install riemann
  sudo: yes
  apt:
    deb: "{{ riemann_download_dir }}/riemann-{{ riemann_version }}_all.deb"

- name: Install Riemann dashboard
  sudo: yes
  shell: "/usr/local/rvm/bin/rvm all do gem install riemann-dash"
  changed_when: False

- name: Upload riemann_cond_dt plugin jar
  copy:
    src: riemann_cond_dt.jar
    dest: /usr/lib/riemann_cond_dt.jar
    owner: "{{ riemann_user }}"
    group: "{{ riemann_user }}"
    mode: 0755

- name: Config used to start riemann
  sudo: yes
  template:
    src: "riemann.conf.j2"
    dest: /etc/riemann/riemann.config
    owner: "{{ riemann_user }}"
    group: "{{ riemann_user }}"
    mode: 0644

- name: Default config for riemann
  sudo: yes
  template:
    src: "riemann_default.conf.j2"
    dest: /etc/default/riemann
    mode: 0644

- name: Create log directory for riemann
  sudo: yes
  file:
    path: "{{ riemann_log_dir }}"
    state: "directory"
    owner: "{{ riemann_user }}"
    group: "{{ riemann_user }}"
    mode: 0755

- name: Create conf directory for riemann
  sudo: yes
  file:
    path: "{{ riemann_conf_dir }}/conf.d"
    state: "directory"
    owner: "{{ riemann_user }}"
    group: "{{ riemann_user }}"
    mode: 0755

- name: Create dashboard configuration file
  sudo: yes
  template:
    src: "dashboard.conf.j2"
    dest: "{{ riemann_conf_dir }}/dashboard.conf"
    owner: "{{ riemann_user }}"
    group: "{{ riemann_user }}"
    mode: 0644

- name: Create dashboard upstart script
  sudo: yes
  template:
    src: "dashboard-upstart.conf.j2"
    dest: /etc/init/riemann-dash.conf
    mode: 0644
  notify: restart riemann-dash
